---
  - name: Adds files under root users directory
    hosts: localhost
    tasks: 
      - name:  Adding files under root users
        file: 
          path: /root/test_config1
          state: touch
          mode: u=rw,g=rw,o=r
      - name: Adding files under root users
        file: 
          path: /root/test_config2
          state: touch
          mode: u=rw,g=rw,o=r 
      - name: Adding files under root users
        file: 
          path: /root/test_config3
          state: touch
          mode: u=rw,g=rw,o=r